syntax = "proto3";

package gateway.domain.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

service DomainService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Verify(VerifyRequest) returns (VerifyResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc List(ListRequest) returns (ListResponse);
}

message CreateRequest {
  string url = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uri = true
  ];
}
message CreateResponse {}

message GetRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message GetResponse {
  Domain domain = 1;
}

message VerifyRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message VerifyResponse {
  Domain domain = 1;
}

message ListRequest {}
message ListResponse {
  repeated Domain domains = 1;
}

message DeleteRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message DeleteResponse {}

message Domain {
  string id = 1;
  string user_id = 2;
  string url = 3;
  string txt = 4;
  google.protobuf.Timestamp verified_at = 5;
  google.protobuf.Timestamp created_at = 7;
  string created_by = 8;
  google.protobuf.Timestamp updated_at = 9;
  string updated_by = 10;
}
