syntax = "proto3";

package gateway.profile.v1;

import "buf/validate/validate.proto";
import "common/profile/v1/profile.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

service GatewayProfileService {
  //  Profile
  rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse);
  rpc Profile(ProfileRequest) returns (ProfileResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);

  // About
  rpc CreateAbout(CreateAboutRequest) returns (CreateAboutResponse);
  rpc About(AboutRequest) returns (AboutResponse);
  rpc UpdateAbout(UpdateAboutRequest) returns (UpdateAboutResponse);

  // Domain
  rpc CreateDomain(CreateDomainRequest) returns (CreateDomainResponse);
  rpc VerifyDomain(VerifyDomainRequest) returns (VerifyDomainResponse);
  rpc UpdateDomainTemplate(UpdateDomainTemplateRequest) returns (UpdateDomainTemplateResponse);
  rpc DeleteDomain(DeleteDomainRequest) returns (DeleteDomainResponse);
  rpc Domains(DomainsRequest) returns (DomainsResponse);
  rpc Domain(DomainRequest) returns (DomainResponse);

  // Education
  rpc CreateEducation(CreateEducationRequest) returns (CreateEducationResponse);
  rpc Education(EducationRequest) returns (EducationResponse);
  rpc UpdateEducation(UpdateEducationRequest) returns (UpdateEducationResponse);
  rpc DeleteEducation(DeleteEducationRequest) returns (DeleteEducationResponse);
  rpc Educations(EducationsRequest) returns (EducationsResponse);

  // Experience
  rpc CreateExperience(CreateExperienceRequest) returns (CreateExperienceResponse);
  rpc Experience(ExperienceRequest) returns (ExperienceResponse);
  rpc UpdateExperience(UpdateExperienceRequest) returns (UpdateExperienceResponse);
  rpc DeleteExperience(DeleteExperienceRequest) returns (DeleteExperienceResponse);
  rpc Experiences(ExperiencesRequest) returns (ExperiencesResponse);

  // Social
  rpc CreateSocial(CreateSocialRequest) returns (CreateSocialResponse);
  rpc UpdateSocial(UpdateSocialRequest) returns (UpdateSocialResponse);
  rpc DeleteSocial(DeleteSocialRequest) returns (DeleteSocialResponse);
  rpc Socials(SocialsRequest) returns (SocialsResponse);
  rpc SocialIcons(SocialIconsRequest) returns (SocialIconsResponse);
}

// Profile
message Profile {
  string user_id = 1;
  string name = 2;
  string title = 3;
  google.protobuf.Timestamp dob = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message CreateProfileRequest {
  common.profile.v1.CreateUpdateProfile profile = 1 [(buf.validate.field).required = true];
  google.protobuf.Timestamp dob = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).cel = {
      id: "dob_eighteen_plus"
      message: "You must be at least 18 years old."
      expression: "this <= now - duration('568036800s')"
    }
  ];
}

message CreateProfileResponse {}

message ProfileRequest {}

message ProfileResponse {
  Profile profile = 1;
}

message UpdateProfileRequest {
  common.profile.v1.CreateUpdateProfile profile = 1 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateProfileResponse {
  Profile profile = 1;
}

// About
message About {
  string user_id = 1;
  string about = 2;
  google.protobuf.Timestamp updated_at = 3;
}

message CreateAboutRequest {
  string about = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {min_len: 20}
  ];
}

message CreateAboutResponse {
  About about = 1;
}

message AboutRequest {}

message AboutResponse {
  About about = 1;
}

message UpdateAboutRequest {
  string about = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 1000
    }
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message UpdateAboutResponse {
  About about = 1;
}

// Domain
message CreateDomainRequest {
  string hostname = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 253
      hostname: true
    }
  ];
}

message CreateDomainResponse {}

message VerifyDomainRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string txt = 2 [(buf.validate.field).required = true];
  string hostname = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 253
      hostname: true
    }
  ];
  google.protobuf.Timestamp updated_at = 4 [(buf.validate.field).required = true];
}

message VerifyDomainResponse {}

message UpdateDomainTemplateRequest {
  string template_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message UpdateDomainTemplateResponse {}

message DeleteDomainRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string hostname = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 253
      hostname: true
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message DeleteDomainResponse {}

message DomainsRequest {}

message DomainsResponse {
  repeated common.profile.v1.Domain domains = 1;
}

message DomainRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DomainResponse {
  string id = 1;
  string user_id = 2;
  string template_id = 3;
  string template = 4;
  string template_icon = 5;
  string hostname = 6;
  string txt = 7;
  string nameserver = 8;
  bool verified = 9;
  google.protobuf.Timestamp updated_at = 10;
}

// Education
message Education {
  string id = 1;
  string user_id = 2;
  string school = 3;
  string degree = 4;
  google.protobuf.StringValue affiliation = 5;
  google.protobuf.StringValue field_of_study = 6;
  google.protobuf.StringValue concentration = 7;
  google.protobuf.Timestamp start_date = 8;
  google.protobuf.Timestamp end_date = 9;
  string address = 10;
  google.protobuf.StringValue description = 11;
  google.protobuf.Timestamp updated_at = 12;
}

message CreateEducationRequest {
  common.profile.v1.CreateUpdateEducation education = 1 [(buf.validate.field).required = true];
}

message CreateEducationResponse {}

message EducationRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message EducationResponse {
  Education education = 1;
}

message DeleteEducationRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message DeleteEducationResponse {}

message EducationsRequest {}

message EducationsResponse {
  repeated common.profile.v1.Education educations = 1;
}

message UpdateEducationRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  common.profile.v1.CreateUpdateEducation education = 2 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateEducationResponse {}

// Experience
message Experience {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string company_name = 4;
  string location = 5;
  string location_type = 6;
  google.protobuf.Timestamp start_date = 7;
  google.protobuf.Timestamp end_date = 8;
  google.protobuf.StringValue description = 9;
  google.protobuf.Timestamp updated_at = 10;
}

message CreateExperienceRequest {
  common.profile.v1.CreateUpdateExperience experience = 1 [(buf.validate.field).required = true];
}

message CreateExperienceResponse {}

message ExperienceRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message ExperienceResponse {
  Experience experience = 1;
}

message UpdateExperienceRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  common.profile.v1.CreateUpdateExperience experience = 2 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateExperienceResponse {}

message DeleteExperienceRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message DeleteExperienceResponse {}

message ExperiencesRequest {}

message ExperiencesResponse {
  repeated common.profile.v1.Experience experiences = 1;
}

// Social
message Social {
  string id = 1;
  string user_id = 2;
  string icon_id = 3;
  string username = 4;
  string name = 5;
  string social = 6;
  string icon = 7;
  google.protobuf.Timestamp updated_at = 8;
}
message SocialIconsRequest {}

message SocialIconsResponse {
  repeated common.profile.v1.Icon icons = 1;
}

message CreateSocialRequest {
  string icon_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string username = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-z0-9][a-z0-9._-]*[a-z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "username_no_consecutive_dots_underscore_hyphen"
      message: "username must not contain consecutive dots or underscore or hyphen"
      expression: "!this.matches('.*([._-]{2,}).*')"
    }
  ];
}

message CreateSocialResponse {}

message UpdateSocialRequest {
  common.profile.v1.UpdateSocial social = 1 [(buf.validate.field).required = true];
}

message UpdateSocialResponse {}

message DeleteSocialRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message DeleteSocialResponse {}

message SocialsRequest {}

message SocialsResponse {
  repeated Social socials = 1;
}
