syntax = "proto3";

package gateway.experience.v1;

import "buf/validate/validate.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

enum LocationType {
  LOCATION_TYPE_UNSPECIFIED = 0;
  LOCATION_TYPE_REMOTE = 1;
  LOCATION_TYPE_HYBRID = 2;
  LOCATION_TYPE_ONSITE = 3;
}

service ExperienceService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc List(ListRequest) returns (ListResponse);
}

message CreateRequest {
  string title = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  string company_name = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  string location = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  LocationType location_type = 4 [(buf.validate.field).required = true];
  google.protobuf.Timestamp start_date = 5 [(buf.validate.field).required = true];
  google.protobuf.Timestamp end_date = 6;
  google.protobuf.StringValue description = 7;
}

message CreateResponse {
  Experience experience = 1;
}

message GetRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}
message GetResponse {
  Experience experience = 1;
}

message UpdateRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  optional string title = 2 [(buf.validate.field).string = {
    min_len: 5
    max_len: 64
  }];
  optional string company_name = 3 [(buf.validate.field).string = {
    min_len: 5
    max_len: 64
  }];
  optional string location = 4 [(buf.validate.field).string = {
    min_len: 5
    max_len: 64
  }];
  LocationType location_type = 5;
  google.protobuf.Timestamp start_date = 6;
  google.protobuf.Timestamp end_date = 7;
  google.protobuf.StringValue description = 8;
  google.protobuf.Timestamp updated_at = 9 [(buf.validate.field).required = true];
  google.protobuf.FieldMask update_mask = 10 [(buf.validate.field).required = true];
}

message UpdateResponse {}

message DeleteRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}
message DeleteResponse {}

message ListRequest {}
message ListResponse {
  repeated Experience experiences = 1;
}

message Experience {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string company_name = 4;
  string location = 5;
  LocationType location_type = 6;
  google.protobuf.Timestamp start_date = 7;
  google.protobuf.Timestamp end_date = 8;
  google.protobuf.StringValue description = 9;
  google.protobuf.Timestamp created_at = 10;
  string created_by = 11;
  google.protobuf.Timestamp updated_at = 12;
  string updated_by = 13;
}
