syntax = "proto3";

package auth.v1;

import "buf/validate/validate.proto";
import "common/password/v1/password.proto";
import "google/protobuf/timestamp.proto";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc LoginTwoFactor(LoginTwoFactorRequest) returns (LoginTwoFactorResponse);
  rpc ForgetPassword(ForgetPasswordRequest) returns (ForgetPasswordResponse);
  rpc Verification(VerificationRequest) returns (VerificationResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
  rpc AccountVerification(AccountVerificationRequest) returns (AccountVerificationResponse);
  rpc ResendAccountVerification(ResendAccountVerificationRequest) returns (ResendAccountVerificationResponse);
}

message RegisterRequest {
  string name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 24
      pattern: "^[a-zA-Z]+( [a-zA-Z]+)*$"
    }
  ];
  string email = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.email = true
  ];
  common.password.v1.Password password = 3 [(buf.validate.field).required = true];
  common.password.v1.Password confirm_password = 4 [(buf.validate.field).required = true];
  string phone = 5 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 10
      max_len: 16
      pattern: "^\\+[1-9]\\d{1,14}$"
    }
  ];
  google.protobuf.Timestamp dob = 6 [
    (buf.validate.field).required = true,
    (buf.validate.field).cel = {
      id: "dob_eighteen_plus"
      message: "You must be at least 18 years old to register."
      expression: "this <= now - duration('568036800s')"
    }
  ];

  option (buf.validate.message).cel = {
    id: "password_match"
    expression: "this.password.value == this.confirm_password.value"
    message: "passwords must match"
  };
}

message RegisterResponse {
  string session = 1;
}

message LoginRequest {
  string email = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.email = true
  ];
  common.password.v1.Password password = 2 [(buf.validate.field).required = true];
}

message LoginResponse {
  oneof response {
    string session = 1;
    Token token = 2;
    string verification = 3;
  }
}

message Token {
  string access = 1;
  string refresh = 2;
  google.protobuf.Timestamp expire_at = 3;
}

message ForgetPasswordRequest {
  string email = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.email = true
  ];
}

message ForgetPasswordResponse {
  oneof response {
    string session = 1;
    string verification = 2;
  }
}

message VerificationRequest {
  string session = 1 [(buf.validate.field).required = true];
  string code = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.len = 8
  ];
}

message VerificationResponse {
  string session = 1;
}

message ResetPasswordRequest {
  string session = 1 [(buf.validate.field).required = true];
  common.password.v1.Password password = 2 [(buf.validate.field).required = true];
  common.password.v1.Password confirm_password = 3 [(buf.validate.field).required = true];

  option (buf.validate.message).cel = {
    id: "password_miss_match"
    expression: "this.password.value == this.confirm_password.value"
    message: "Password and confirm password must match"
  };
}

message ResetPasswordResponse {}

message LoginTwoFactorRequest {
  string session = 1 [(buf.validate.field).required = true];

  oneof code {
    string totp = 2 [
      (buf.validate.field).string.len = 6,
      (buf.validate.field).string.pattern = "^[0-9]+$"
    ];
    string recovery = 3 [
      (buf.validate.field).string.len = 10,
      (buf.validate.field).string.pattern = "^[A-Z0-9]+$"
    ];
  }
}

message LoginTwoFactorResponse {
  Token token = 1;
}

message AccountVerificationRequest {
  string session = 1 [(buf.validate.field).required = true];
  string code = 2 [(buf.validate.field).string = {
    len: 8
    pattern: "^[A-Z0-9]+$"
  }];
}

message AccountVerificationResponse {
  oneof response {
    string session = 1;
    Token token = 2;
  }
}

message ResendAccountVerificationRequest {
  string session = 1 [(buf.validate.field).required = true];
}

message ResendAccountVerificationResponse {
  string session = 1;
}
