syntax = "proto3";

package gateway.authentication.v1;

import "buf/validate/validate.proto";
import "common/password/v1/password.proto";
import "google/protobuf/timestamp.proto";

service GatewayAuthenticationService {
  rpc PasswordVerification(PasswordVerificationRequest) returns (PasswordVerificationResponse);
  rpc PasswordSessionVerification(PasswordSessionVerificationRequest) returns (PasswordSessionVerificationResponse);

  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);

  rpc EnableTwoFactor(EnableTwoFactorRequest) returns (EnableTwoFactorResponse);
  rpc ConfirmTwoFactor(ConfirmTwoFactorRequest) returns (ConfirmTwoFactorResponse);

  rpc Role(RoleRequest) returns (RoleResponse);

  rpc Profile(ProfileRequest) returns (ProfileResponse);

  rpc Logout(LogoutRequest) returns (LogoutResponse);
}

enum PasswordVerificationMethod {
  PASSWORD_VERIFICATION_METHOD_UNSPECIFIED = 0;
  PASSWORD_VERIFICATION_METHOD_CHANGE = 1;
  PASSWORD_VERIFICATION_METHOD_ENABLED = 2;
  PASSWORD_VERIFICATION_METHOD_DISABLED = 3;
}

message PasswordVerificationRequest {
  common.password.v1.Password password = 1 [(buf.validate.field).required = true];
  PasswordVerificationMethod method = 2 [(buf.validate.field).required = true];
}

message PasswordVerificationResponse {
  string session = 1;
}

message PasswordSessionVerificationRequest {
  string session = 1 [(buf.validate.field).required = true];
  oneof code {
    string totp = 2 [(buf.validate.field).string = {
      len: 6
      pattern: "^[0-9]+$"
    }];
    string email = 3 [(buf.validate.field).string = {
      len: 8
      pattern: "^[A-Z0-9]+$"
    }];
    string recovery = 4 [(buf.validate.field).string = {
      len: 10
      pattern: "^[A-Z0-9]+$"
    }];
  }
}

message PasswordSessionVerificationResponse {
  string session = 1;
}

message ChangePasswordRequest {
  string session = 1 [(buf.validate.field).required = true];
  common.password.v1.Password password = 2 [(buf.validate.field).required = true];
  common.password.v1.Password confirm_password = 3 [(buf.validate.field).required = true];

  option (buf.validate.message).cel = {
    id: "password_miss_match"
    expression: "this.password.value == this.confirm_password.value"
    message: "Password and confirm password must match"
  };
}

message ChangePasswordResponse {}

message EnableTwoFactorRequest {
  string session = 1 [(buf.validate.field).required = true];
  string code = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      len: 8
      pattern: "^[A-Z0-9]+$"
    }
  ];
}

message EnableTwoFactorResponse {
  string session = 1;
  string uri = 2;
  string key = 3;
}

message ConfirmTwoFactorRequest {
  string session = 1 [(buf.validate.field).required = true];
  string code = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      len: 6
      pattern: "^[0-9]+$"
    }
  ];
}

message ConfirmTwoFactorResponse {
  repeated string codes = 1;
}

message RoleRequest {}

message RoleResponse {
  string role = 1;
}

message ProfileRequest {}

message ProfileResponse {
  string email = 1;
  string username = 2;
  string phone = 3;
  string status = 4;
  bool two_factor_enabled = 5;
  google.protobuf.Timestamp last_password_changed_at = 6;
  google.protobuf.Timestamp account_created_at = 7;
}

message LogoutRequest {}

message LogoutResponse {}
