syntax = "proto3";

package gateway.social.v1;

import "buf/validate/validate.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";

service SocialService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc List(ListRequest) returns (ListResponse);
}

message CreateRequest {
  string platform_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string username = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
}

message CreateResponse {
  Social social = 1;
}

message UpdateRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string username = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateResponse {
  Social social = 1;
}

message DeleteRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message DeleteResponse {}

message ListRequest {}

message ListResponse {
  repeated Social socials = 1;
}

message Social {
  string id = 1;
  string user_id = 2;
  string username = 3;
  string name = 4;
  string url = 5;
  string logo_url = 6;
  string color = 7;
  google.protobuf.Timestamp created_at = 8;
  string created_by = 9;
  google.protobuf.Timestamp updated_at = 10;
  string updated_by = 11;
}
