syntax = "proto3";

package root.authentication.v1;

import "buf/validate/validate.proto";
import "common/authentication/v1/authentication.proto";
import "google/protobuf/timestamp.proto";

service RootAuthenticationService {
  rpc UpdateRole(UpdateRoleRequest) returns (UpdateRoleResponse);
  rpc UpdateStatus(UpdateStatusRequest) returns (UpdateStatusResponse);
  rpc UpdateUsername(UpdateUsernameRequest) returns (UpdateUsernameResponse);

  rpc User(UserRequest) returns (UserResponse);
  rpc Users(UsersRequest) returns (UsersResponse);
}

message UpdateRoleRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string role = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 64
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateRoleResponse {}

message UpdateStatusRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string status = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 64
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}
message UpdateStatusResponse {}

message UpdateUsernameRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  common.authentication.v1.Username username = 2 [(buf.validate.field).required = true];
}

message UpdateUsernameResponse {}

message UsersRequest {}

message UsersResponse {
  repeated UserSummary users = 1;
}

message UserSummary {
  string id = 1;
  string username = 2;
  string email = 3;
  bool email_verified = 4;
  string phone = 5;
  bool phone_verified = 6;
}

message UserRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message UserResponse {
  string id = 1;
  string email = 2;
  string username = 3;
  string phone = 4;
  string role = 5;
  string status = 6;
  bool email_verified = 7;
  google.protobuf.Timestamp email_verified_at = 8;
  bool phone_verified = 9;
  google.protobuf.Timestamp phone_verified_at = 10;
  bool two_factor = 11;
  google.protobuf.Timestamp last_password_updated_at = 12;
  google.protobuf.Timestamp created_at = 13;
  string created_by = 14;
  google.protobuf.Timestamp updated_at = 15;
  string updated_by = 16;
  string created_by_username = 17;
  string updated_by_username = 18;
}
