syntax = "proto3";

package root.authentication.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

service RootAuthenticationService {
  rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
  rpc User(UserRequest) returns (UserResponse);
  rpc Users(UsersRequest) returns (UsersResponse);
}

message UpdateUserRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string username = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 64
      pattern: "^[a-z]+[0-9]*$"
    }
  ];
  string role = 3 [(buf.validate.field).required = true];
  string status = 4 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 5 [(buf.validate.field).required = true];
}

message UpdateUserResponse {}

message UsersRequest {}

message UsersResponse {
  repeated UserSummary users = 1;
}

message UserSummary {
  string id = 1;
  string username = 2;
  string phone = 3;
}

message UserRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message UserResponse {
  string id = 1;
  string email = 2;
  string username = 3;
  string phone = 4;
  string role = 5;
  string status = 6;
  bool email_verified = 7;
  bool two_factor = 8;
  google.protobuf.Timestamp last_password_updated_at = 9;
  google.protobuf.Timestamp created_at = 10;
  string created_by = 11;
  google.protobuf.Timestamp updated_at = 12;
  string updated_by = 13;
}
