syntax = "proto3";

package root.profile.v1;

import "buf/validate/validate.proto";
import "common/profile/v1/profile.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

service RootProfileService {
  // Profile
  rpc Profile(ProfileRequest) returns (ProfileResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);

  // About
  rpc About(AboutRequest) returns (AboutResponse);
  rpc UpdateAbout(UpdateAboutRequest) returns (UpdateAboutResponse);

  // Domains
  rpc Domains(DomainsRequest) returns (DomainsResponse);
  rpc DeleteDomain(DeleteDomainRequest) returns (DeleteDomainResponse);

  // Nameservers
  rpc Nameservers(NameserversRequest) returns (NameserversResponse);
  rpc CreateNameserver(CreateNameserverRequest) returns (CreateNameserverResponse);
  rpc DeleteNameserver(DeleteNameserverRequest) returns (DeleteNameserverResponse);

  // Educations
  rpc Education(EducationRequest) returns (EducationResponse);
  rpc UpdateEducation(UpdateEducationRequest) returns (UpdateEducationResponse);
  rpc Educations(EducationsRequest) returns (EducationsResponse);
  rpc DeleteEducation(DeleteEducationRequest) returns (DeleteEducationResponse);

  // Experience
  rpc Experience(ExperienceRequest) returns (ExperienceResponse);
  rpc UpdateExperience(UpdateExperienceRequest) returns (UpdateExperienceResponse);
  rpc Experiences(ExperiencesRequest) returns (ExperiencesResponse);
  rpc DeleteExperience(DeleteExperienceRequest) returns (DeleteExperienceResponse);

  // Icons
  rpc Icons(IconsRequest) returns (IconsResponse);
  rpc Icon(IconRequest) returns (IconResponse);
  rpc CreateIcon(CreateIconRequest) returns (CreateIconResponse);
  rpc UpdateIcon(UpdateIconRequest) returns (UpdateIconResponse);
  rpc DeleteIcon(DeleteIconRequest) returns (DeleteIconResponse);

  // Social
  rpc UpdateSocial(UpdateSocialRequest) returns (UpdateSocialResponse);
  rpc Socials(SocialsRequest) returns (SocialsResponse);
  rpc DeleteSocial(DeleteSocialRequest) returns (DeleteSocialResponse);
}

// Profile
message ProfileRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message ProfileResponse {
  common.profile.v1.Profile profile = 1;
}

message UpdateProfileRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  common.profile.v1.CreateUpdateProfile profile = 2 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateProfileResponse {
  common.profile.v1.Profile profile = 1;
}

// About
message AboutRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message AboutResponse {
  common.profile.v1.About about = 1;
}

message UpdateAboutRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string about = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 1000
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateAboutResponse {
  common.profile.v1.About about = 1;
}

// Domain
message DomainsRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DomainsResponse {
  repeated common.profile.v1.Domains domains = 1;
}

message DeleteDomainRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DeleteDomainResponse {}

// Education
message EducationRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message EducationResponse {
  common.profile.v1.Education education = 1;
}

message UpdateEducationRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  common.profile.v1.CreateUpdateEducation education = 3 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 4 [(buf.validate.field).required = true];
}

message UpdateEducationResponse {}

message EducationsRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message EducationsResponse {
  repeated common.profile.v1.Educations educations = 1;
}

message DeleteEducationRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DeleteEducationResponse {}

message DeleteEducationsRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DeleteEducationsResponse {}

// Experience
message ExperienceRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message ExperienceResponse {
  common.profile.v1.Experience experience = 1;
}

message UpdateExperienceRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  common.profile.v1.CreateUpdateExperience experience = 3 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 4 [(buf.validate.field).required = true];
}

message UpdateExperienceResponse {}

message ExperiencesRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message ExperiencesResponse {
  repeated common.profile.v1.Experiences experiences = 1;
}

message DeleteExperienceRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DeleteExperienceResponse {}

message DeleteExperiencesRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DeleteExperiencesResponse {}

// Icon
message IconsRequest {}

message IconsResponse {
  repeated common.profile.v1.Icons icons = 1;
}

message IconRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message IconResponse {
  string id = 1;
  string name = 2;
  string site = 3;
  google.protobuf.StringValue site_suffix = 4;
  string url = 5;
  string slug = 6;
  string color = 7;
  google.protobuf.Timestamp created_at = 8;
  string created_by = 9;
  google.protobuf.Timestamp updated_at = 10;
  string updated_by = 11;
}

message CreateIconRequest {
  CreateUpdateIcon icon = 1 [(buf.validate.field).required = true];
}

message CreateIconResponse {}

message UpdateIconRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  CreateUpdateIcon icon = 2 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message UpdateIconResponse {}

message DeleteIconRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message DeleteIconResponse {}

message DeleteIconsRequest {}

message DeleteIconsResponse {}

// Social
message UpdateSocialRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  common.profile.v1.UpdateSocial social = 2 [(buf.validate.field).required = true];
}

message UpdateSocialResponse {}

message SocialsRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message SocialsResponse {
  repeated common.profile.v1.Socials socials = 1;
}

message CreateUpdateIcon {
  string name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 1
      max_len: 24
      pattern: "^[a-zA-Z0-9]+( [a-zA-Z0-9]+)*$"
    },
    (buf.validate.field).cel = {
      id: "name_no_consecutive_dots_underscore_hyphen"
      message: "name must not contain consecutive dots or underscore or hyphen"
      expression: "!this.matches('.*([ ]{2,}).*')"
    }
  ];
  string site = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 254
      hostname: true
    }
  ];
  google.protobuf.StringValue site_suffix = 3 [
    (buf.validate.field).string = {
      min_len: 1
      max_len: 32
      pattern: "^\\/[a-zA-Z0-9_@.~-]*\\/?$"
    },
    (buf.validate.field).cel = {
      id: "site_suffix_no_consecutive_repeat_specials"
      message: "site_suffix must not contain consecutive slashes, dots, underscores, or hyphens"
      expression: "!this.matches('.*(//|\\\\.\\\\.|--|__|~~).*')"
    }
  ];
  string url = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 4
      max_len: 254
      hostname: true
    }
  ];
  string slug = 5 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 1
      max_len: 128
      pattern: "^[a-zA-Z0-9]([a-zA-Z0-9/-]*[a-zA-Z0-9])?(\\.svg)?$"
    },
    (buf.validate.field).cel = {
      id: "slug_no_consecutive_dots_underscore_hyphen"
      message: "slug must not contain consecutive dots or underscore or hyphen"
      expression: "!this.matches('.*([/-]{2,}).*')"
    }
  ];
  string color = 6 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      len: 7
      pattern: "^#[0-9a-fA-F]{6}$"
    }
  ];
}

message DeleteSocialRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DeleteSocialResponse {}

message DeleteSocialsRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message DeleteSocialsResponse {}

// Nameserver
message CreateNameserverRequest {
  string ip_type = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      in: [
        "A",
        "AAAA"
      ]
    }
  ];
  string ip = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.ip = true
  ];

  option (buf.validate.message).cel = {
    id: "ip_type_mismatch"
    message: "IP address version must match record type (A requires IPv4, AAAA requires IPv6)"
    expression: "(this.ip_type == 'A' && this.ip.isIp(4)) || (this.ip_type == 'AAAA' && this.ip.isIp(6))"
  };
}

message CreateNameserverResponse {}

message DeleteNameserverRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message DeleteNameserverResponse {}

message NameserversRequest {}

message NameserversResponse {
  repeated Nameservers nameservers = 1;
}

message Nameservers {
  string id = 1;
  string ip_type = 2;
  string ip = 3;
  google.protobuf.Timestamp created_at = 4;
  string created_by = 5;
  google.protobuf.Timestamp updated_at = 6;
  string updated_by = 7;
}
