syntax = "proto3";

package gateway.about.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

service AboutService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
}

message CreateRequest {
  string about = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {min_len: 20}
  ];
}

message CreateResponse {
  About about = 1;
}

message GetRequest {}

message GetResponse {
  About about = 1;
}

message UpdateRequest {
  string about = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {min_len: 20}
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message UpdateResponse {
  About about = 1;
}

message About {
  string user_id = 1;
  string about = 2;
  google.protobuf.Timestamp created_at = 3;
  string created_by = 4;
  google.protobuf.Timestamp updated_at = 5;
  string updated_by = 6;
}
