syntax = "proto3";

package common.password.v1;

import "buf/validate/validate.proto";

message Password {
  string value = 1 [(buf.validate.field).string = {
    min_len: 8
    max_len: 64
  }];

  option (buf.validate.message).cel = {
    id: "password_lower"
    expression: "this.value.matches('.*[a-z].*')"
    message: "Password must contain at least one lowercase letter"
  };

  option (buf.validate.message).cel = {
    id: "password_upper"
    expression: "this.value.matches('.*[A-Z].*')"
    message: "Password must contain at least one uppercase letter"
  };

  option (buf.validate.message).cel = {
    id: "password_number"
    expression: "this.value.matches('.*[0-9].*')"
    message: "Password must contain at least one digit"
  };

  option (buf.validate.message).cel = {
    id: "password_symbol"
    expression: "this.value.matches('.*[!@#$%^&*(),.?\":{}|<>_-].*')"
    message: "Password must contain at least one special symbol"
  };
}
