syntax = "proto3";

package common.profile.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

message Profile {
  string user_id = 1;
  string name = 2;
  string title = 3;
  google.protobuf.Timestamp dob = 4;
  google.protobuf.Timestamp created_at = 5;
  string created_by = 6;
  google.protobuf.Timestamp updated_at = 7;
  string updated_by = 8;
}

message UpdateProfile {
  string name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 24
      pattern: "^[a-zA-Z]+( [a-zA-Z]+)*$"
    }
  ];
  string title = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message About {
  string user_id = 1;
  string about = 2;
  google.protobuf.Timestamp created_at = 3;
  string created_by = 4;
  google.protobuf.Timestamp updated_at = 5;
  string updated_by = 6;
}

message UpdateAbout {
  string about = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {min_len: 20}
  ];
  google.protobuf.Timestamp updated_at = 2 [(buf.validate.field).required = true];
}

message Domains {
  string id = 1;
  string user_id = 2;
  string url = 3;
  string txt = 4;
  bool verified = 5;
  google.protobuf.Timestamp created_at = 7;
  string created_by = 8;
  google.protobuf.Timestamp updated_at = 9;
  string updated_by = 10;
}

message Education {
  string id = 1;
  string user_id = 2;
  string school = 3;
  string degree = 4;
  google.protobuf.StringValue affiliation = 5;
  google.protobuf.StringValue field_of_study = 6;
  google.protobuf.StringValue concentration = 7;
  google.protobuf.Timestamp start_date = 8;
  google.protobuf.Timestamp end_date = 9;
  string address = 10;
  google.protobuf.StringValue description = 11;
  google.protobuf.Timestamp created_at = 12;
  string created_by = 13;
  google.protobuf.Timestamp updated_at = 14;
  string updated_by = 15;
}

message Educations {
  string id = 1;
  string user_id = 2;
  string school = 3;
  string degree = 4;
  google.protobuf.Timestamp start_date = 5;
  google.protobuf.Timestamp end_date = 6;
}

message UpdateEducation {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string school = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 128
    }
  ];
  string degree = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 128
    }
  ];
  google.protobuf.StringValue affiliation = 4;
  google.protobuf.StringValue field_of_study = 5;
  google.protobuf.StringValue concentration = 6;
  google.protobuf.Timestamp start_date = 7 [(buf.validate.field).required = true];
  google.protobuf.Timestamp end_date = 8;
  string address = 9 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 128
    }
  ];
  google.protobuf.StringValue description = 10;
  google.protobuf.Timestamp updated_at = 11 [(buf.validate.field).required = true];

  option (buf.validate.message).cel = {
    id: "education_dates"
    message: "End date cannot be in the future and must be after the start date."
    expression: "!has(this.end_date) || (this.end_date <= now && this.end_date > this.start_date)"
  };
}

message Experiences {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string company_name = 4;
  google.protobuf.Timestamp start_date = 7;
  google.protobuf.Timestamp end_date = 8;
}

message Experience {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string company_name = 4;
  string location = 5;
  string location_type = 6;
  google.protobuf.Timestamp start_date = 7;
  google.protobuf.Timestamp end_date = 8;
  google.protobuf.StringValue description = 9;
  google.protobuf.Timestamp created_at = 10;
  string created_by = 11;
  google.protobuf.Timestamp updated_at = 12;
  string updated_by = 13;
}

message UpdateExperience {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string title = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  string company_name = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  string location = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  string location_type = 5 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.in = "onsite",
    (buf.validate.field).string.in = "hybrid",
    (buf.validate.field).string.in = "remote"
  ];
  google.protobuf.Timestamp start_date = 6 [(buf.validate.field).required = true];
  google.protobuf.Timestamp end_date = 7;
  google.protobuf.StringValue description = 8;
  google.protobuf.Timestamp updated_at = 9 [(buf.validate.field).required = true];

  option (buf.validate.message).cel = {
    id: "experience_dates"
    message: "End date cannot be in the future and must be after the start date."
    expression: "!has(this.end_date) || (this.end_date <= now && this.end_date > this.start_date)"
  };
}

// Social
message UpdateSocial {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string username = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message Socials {
  string id = 1;
  string user_id = 2;
  string platform_id = 3;
  string username = 4;
  string name = 5;
  string url = 6;
  string logo_url = 7;
  string color = 8;
  string url_suffix = 9;
  google.protobuf.Timestamp created_at = 10;
  string created_by = 11;
  google.protobuf.Timestamp updated_at = 12;
  string updated_by = 13;
}

message Platforms {
  string id = 1;
  string name = 2;
  string url = 3;
  string logo_url = 4;
  string color = 5;
  string url_suffix = 6;
}
