syntax = "proto3";

package common.profile.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

message Profile {
  string user_id = 1;
  string name = 2;
  string title = 3;
  google.protobuf.Timestamp dob = 4;
  google.protobuf.Timestamp created_at = 5;
  string created_by = 6;
  google.protobuf.Timestamp updated_at = 7;
  string updated_by = 8;
}

message CreateUpdateProfile {
  string name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 24
      pattern: "^[a-zA-Z][a-zA-Z .'-]*[a-zA-Z.]$"
    },
    (buf.validate.field).cel = {
      id: "name_no_consecutive_dots_underscore_hyphen"
      message: "name must not contain consecutive dots or underscore or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  string title = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 3
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .'&/()-]*[a-zA-Z0-9).]$"
    },
    (buf.validate.field).cel = {
      id: "title_no_consecutive_dots_underscore_hyphen"
      message: "title must not contain consecutive dots or underscore or hyphen"
      expression: "!this.matches('.*([ .\\'&/()-]{2,}).*')"
    }
  ];
}

message About {
  string user_id = 1;
  string about = 2;
  google.protobuf.Timestamp created_at = 3;
  string created_by = 4;
  google.protobuf.Timestamp updated_at = 5;
  string updated_by = 6;
}

message Domains {
  string id = 1;
  string user_id = 2;
  string ip = 3;
  string ip_type = 4;
  string fqdn = 5;
  string txt = 6;
  bool verified = 7;
  google.protobuf.Timestamp created_at = 8;
  string created_by = 9;
  google.protobuf.Timestamp updated_at = 10;
  string updated_by = 11;
}

message CreateUpdateEducation {
  string school = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 3
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "school_no_consecutive_dots_underscore_hyphen"
      message: "school must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  string degree = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "degree_no_consecutive_dots_underscore_hyphen"
      message: "degree must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  google.protobuf.StringValue affiliation = 3 [
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "affiliation_no_consecutive_dots_underscore_hyphen"
      message: "affiliation must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  google.protobuf.StringValue field_of_study = 4 [
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "field_of_study_no_consecutive_dots_underscore_hyphen"
      message: "field_of_study must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  google.protobuf.StringValue concentration = 5 [
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "concentration_no_consecutive_dots_underscore_hyphen"
      message: "concentration must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  google.protobuf.Timestamp start_date = 6 [(buf.validate.field).required = true];
  google.protobuf.Timestamp end_date = 7;
  string address = 8 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 3
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "address_no_consecutive_dots_underscore_hyphen"
      message: "address must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  google.protobuf.StringValue description = 9 [(buf.validate.field).string = {
    min_len: 5
    max_len: 1000
  }];

  option (buf.validate.message).cel = {
    id: "education_dates"
    message: "End date cannot be in the future and must be after the start date."
    expression: "!has(this.end_date) || (this.end_date <= now && this.end_date > this.start_date)"
  };
}

message Education {
  string id = 1;
  string user_id = 2;
  string school = 3;
  string degree = 4;
  google.protobuf.StringValue affiliation = 5;
  google.protobuf.StringValue field_of_study = 6;
  google.protobuf.StringValue concentration = 7;
  google.protobuf.Timestamp start_date = 8;
  google.protobuf.Timestamp end_date = 9;
  string address = 10;
  google.protobuf.StringValue description = 11;
  google.protobuf.Timestamp created_at = 12;
  string created_by = 13;
  google.protobuf.Timestamp updated_at = 14;
  string updated_by = 15;
}

message Educations {
  string id = 1;
  string user_id = 2;
  string school = 3;
  string degree = 4;
  google.protobuf.Timestamp start_date = 5;
  google.protobuf.Timestamp end_date = 6;
}

message Experiences {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string company_name = 4;
  google.protobuf.Timestamp start_date = 7;
  google.protobuf.Timestamp end_date = 8;
}

message Experience {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string company_name = 4;
  string location = 5;
  string location_type = 6;
  google.protobuf.Timestamp start_date = 7;
  google.protobuf.Timestamp end_date = 8;
  google.protobuf.StringValue description = 9;
  google.protobuf.Timestamp created_at = 10;
  string created_by = 11;
  google.protobuf.Timestamp updated_at = 12;
  string updated_by = 13;
}

message CreateUpdateExperience {
  string title = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "title_no_consecutive_dots_underscore_hyphen"
      message: "title must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  string company_name = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "company_name_no_consecutive_dots_underscore_hyphen"
      message: "company_name must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  string location = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-zA-Z0-9][a-zA-Z0-9 .,'-]*[a-zA-Z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "location_no_consecutive_dots_underscore_hyphen"
      message: "location must not contain consecutive space or dots or , or hyphen"
      expression: "!this.matches('.*([ .,\\'-]{2,}).*')"
    }
  ];
  string location_type = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      in: [
        "onsite",
        "hybrid",
        "remote"
      ]
    }
  ];
  google.protobuf.Timestamp start_date = 5 [(buf.validate.field).required = true];
  google.protobuf.Timestamp end_date = 6;
  google.protobuf.StringValue description = 7 [(buf.validate.field).string = {
    min_len: 5
    max_len: 1000
  }];

  option (buf.validate.message).cel = {
    id: "experience_dates"
    message: "End date cannot be in the future and must be after the start date."
    expression: "!has(this.end_date) || (this.end_date <= now && this.end_date > this.start_date)"
  };
}

// Social
message UpdateSocial {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string username = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 5
      max_len: 64
      pattern: "^[a-z0-9][a-z0-9._-]*[a-z0-9]$"
    },
    (buf.validate.field).cel = {
      id: "username_no_consecutive_dots"
      message: "username must not contain consecutive dots or underscore or hyphen"
      expression: "!this.matches('.*([._-]{2,}).*')"
    }
  ];
  google.protobuf.Timestamp updated_at = 3 [(buf.validate.field).required = true];
}

message Socials {
  string id = 1;
  string user_id = 2;
  string icon_id = 3;
  string username = 4;
  string name = 5;
  string site = 6;
  string icon = 7;
  google.protobuf.Timestamp created_at = 8;
  string created_by = 9;
  google.protobuf.Timestamp updated_at = 10;
  string updated_by = 11;
}

message Icons {
  string id = 1;
  string name = 2;
  string icon = 3;
}

message Exists {
  bool profile = 1;
  bool about = 2;
  bool educations = 3;
  bool experiences = 4;
  bool socials = 5;
}
